/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function detectInjection(text: string, threshold?: number | undefined | null): JsScanResult

export declare function detectPii(text: string, piiTypes?: Array<string> | undefined | null): JsScanResult

export declare function isSafe(text: string): boolean

export interface JsPiiFinding {
  entityType: string
  start: number
  end: number
  text: string
  confidence: number
}

export interface JsScanOptions {
  detectPii?: boolean
  detectInjection?: boolean
  piiTypes?: Array<string>
  injectionThreshold?: number
  redact?: boolean
  redactWith?: string
}

export interface JsScanResult {
  isSafe: boolean
  piiFindings: Array<JsPiiFinding>
  injectionScore: number
  injectionLabels: Array<string>
  redactedText?: string
  latencyUs: number
}

export declare function redact(text: string, redactWith?: string | undefined | null): string

export declare function scan(text: string, options?: JsScanOptions | undefined | null): JsScanResult
